const AGREEMENT_REJECTION_REASONS = [
  'MISSING_DOCUMENT',
  'INVALID_INFORMATION',
  'STUDENT_WITHDREW',
  'OTHER',
];

const MIN_INTERNSHIP_DURATION_DAYS = 20;
const MIN_INTERNSHIP_START_LEAD_DAYS = 15;

module.exports = {
  AGREEMENT_REJECTION_REASONS,
  MIN_INTERNSHIP_DURATION_DAYS,
  MIN_INTERNSHIP_START_LEAD_DAYS,
};
